# =========================
# DATABASE CONFIGURATION
# =========================

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=H3Hasbi
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/employee_management

# =========================
# CORS
# =========================

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE
quarkus.http.cors.headers=*

# =========================
# HIBERNATE ORM
# =========================

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# =========================
# SWAGGER / OPENAPI
# =========================

quarkus.swagger-ui.always-include=true

# =========================
# SERVER
# =========================

quarkus.http.port=8080